@startuml elemente

package "S-CORE Repo" {
  class Platform {
    + SEooC: bool
    --
    Objectives
    Stakeholder Requirements
    Platform Architecture
    SW-Platform Assumptions of use
    Platform Integration Tests
  }

  class Feature {
    --
    Feature Requirements
    Feature Architecture
    Feature Integration Tests
    Feature Safety/Security Analysis
    Feature Assumptions of use
  }
}

package "SW-Module Repo" {
  class Component {
    + SEooC: bool
    --
    Component Requirements
    Component Architecture
    Component Integration Tests
    Component Safety/Security Analysis
    Component Assumption of use
  }

  class Unit {
    --
    Detailed Design
    Source Code
    Unit Test
  }
}

package "Integration Repo" {
}

' Package Relationships
"Integration Repo" ..> "S-CORE Repo" : derives from
"Integration Repo" ..> "SW-Module Repo" : uses
"S-CORE Repo" -[hidden]d- "SW-Module Repo"

' Relationships
Platform "1" *-- "n" Feature
Feature "1" o-- "n" Component
Component "1" o-- "n" Component : contains
Component "1" o-d- "n" Unit

@enduml
