# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Problem Report
description: Issue to track a bug
title: "Bug: Your bugfix title"
labels: ["codeowner_review"]
body:
  - type: markdown
    attributes:
      value: "## <ins>Bug Ticket creation</ins>"
  - type: textarea
    attributes:
      label: Description
      description: |
        Description of the Bug
        Root cause / Impact / Notification required?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Analysis results
      description: |
        Documentation of the analysis results
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: |
        Documentation of the solution
        Link to Pull Request containing the solution
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Error Occurrence  Rate
      options:
        - Single Event
        - Sporadic
        - Highly Intermittent
        - Reproducible
  - type: textarea
    attributes:
      label: How to reproduce
      description: How to reproduce?
  - type: textarea
    attributes:
      label: Supporting Information
      description: |
        During which operational state did the issue occur
        Observations / Screenshots / Traces
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Classification
      options:
        - minor
        - major
        - critical
        - blocker
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Affected Version
      options:
        - pre-0.5
        - 0.5
        - 1.0
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Expected Closure Version
      options:
        - 0.5
        - 1.0
      default: 0
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Category
      options:
        - label: Safety Related
        - label: Security Related
  - type: textarea
    attributes:
      label: ASIL classification
      description: Add ASIL classification, e.g. ASIL_B or ASIL_D
    validations:
      required: false
