# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: "Improvement / Task"
description: Issue to track a improvement / task
title: "Improvement: Your Improvement title"
labels: ["codeowner_review"]
body:
  - type: textarea
    attributes:
      label: What
      description: |
        - Goal of the Improvement / Task
        - If Req/Architecture is affected, the template of
        [Change Management](https://eclipse-score.github.io/process_description/main/process_areas/change_management/guidance/change_management_impact_analysis_template.html) needs to be used
    validations:
      required: true
  - type: textarea
    attributes:
      label: How
      description: Details on implementation approach
    validations:
      required: false
  - type: textarea
    attributes:
      label: Estimates for realization
      description: |
        - Estimate the effort, resources, risk for the realization
        - Impact to users of the feature
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Category
      options:
        - label: Affects Detailed Design
  - type: checkboxes
    attributes:
      label: Requirements / Architecture
      options:
        - label: Requirements / Architecture are not affected by this change?
          required: true
