@startuml Work Package Workflow

    (*top) -->"New"

    ' New State
    "New" --> "Analyze"
    "New" --> "Blocked"
    "New" --> "Done"
        note left
          in case work packages is obsolete
        end note

    ' Analyze State
    "Analyze" --> "In Progress"
    "Analyze" --> "Blocked"
    "Analyze" --> "Done"

    ' In Progress State
    "In Progress" --> "Analyze"
        note left
          in case new information
          forces the work package to
          be re-evaluated
        end note
    "In Progress" --> "Blocked"
    "In Progress" --> "Done"

    ' Blocked State
    "Blocked" --> "Analyze"
    "Blocked" --> "In Progress"

    ' Done State
    "Done" --> "Analyze"
    "Done" --> (*)

@enduml
