load("//tools/testing/pytest:defs.bzl", "py_pytest")

py_pytest(
    name = "test_rules_are_working_correctly",
    srcs = [
        "conftest.py",
        "test_rules_are_working_correctly.py",
    ],
)
