#!/usr/bin/env python3
# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""Render the Rust rule catalogue and mapping table, or check they are current."""

import argparse
import csv
import io
import json
import sys
import textwrap
from collections import Counter
from pathlib import Path

BASE = (
    Path(__file__).resolve().parents[1]
    / "docs/contribute/development/rust/coding_rules"
)
HEADER = """..
   # *******************************************************************************
   # Copyright (c) 2026 Contributors to the Eclipse Foundation
   #
   # See the NOTICE file(s) distributed with this work for additional
   # information regarding copyright ownership.
   #
   # This program and the accompanying materials are made available under the
   # terms of the Apache License Version 2.0 which is available at
   # https://www.apache.org/licenses/LICENSE-2.0
   #
   # SPDX-License-Identifier: Apache-2.0
   # *******************************************************************************

"""
PREAMBLE = """.. Generated by tools/render_rust_coding_rules.py; edit _assets/rules.json instead.

.. _rust_coding_rules:

Rust Rule Catalogue
###################

.. document:: Rust Coding Rules Catalogue
   :id: doc__rust_coding_rules_catalogue
   :status: draft
   :version: 1
   :safety: ASIL_B
   :security: YES
   :realizes: wp__sw_development_plan[version==1]

These are draft rules. The proposed levels take effect only after adoption through the
Software Development Plan as described in :ref:`rust_coding_rules_overview`. Enforcement
candidates require validation under :ref:`rust_coding_rules_verification`; a source mapping
does not establish compliance.

.. contents:: Rules
   :local:
   :depth: 1

"""
EXPECTED_RULES = 43
EXPECTED_SOURCES = 179
EXPECTED_CLASSES = {"C1": 15, "C2": 42, "C3": 53, "C4": 36, "C5": 11, "C6": 22}


def paragraph(text):
    return textwrap.fill(text, width=100) + "\n\n"


def validate(rules, rows):
    ids = {r["id"] for r in rules}
    source_ids = {r["misra_cpp_id"] for r in rows}
    if len(ids) != len(rules) or len(source_ids) != len(rows):
        raise ValueError("Duplicate rule or source guideline IDs")
    if len(rules) != EXPECTED_RULES or len(rows) != EXPECTED_SOURCES:
        raise ValueError(
            "Update the documented baseline counts when intentionally changing the catalogue"
        )
    counts = Counter(r["misrust_class"] for r in rows)
    if counts != EXPECTED_CLASSES:
        raise ValueError(
            "The source classifications do not match the pinned MISRust baseline"
        )
    for row in rows:
        linked = set(filter(None, row["score_rule_ids"].split(";")))
        expected = {r["id"] for r in rules if row["misra_cpp_id"] in r["misra_cpp_ids"]}
        if linked != expected or not linked <= ids:
            raise ValueError(f"Inconsistent rule mapping: {row['misra_cpp_id']}")
        retained = row["misrust_class"] in ("C4", "C5", "C6")
        if (row["paper_relevant_set"] == "yes") != retained or (
            retained and not linked
        ):
            raise ValueError(
                f"Missing or incorrect retained-rule mapping: {row['misra_cpp_id']}"
            )
    for rule in rules:
        if not set(rule["misra_cpp_ids"]) <= source_ids:
            raise ValueError(f"Unknown source guideline in {rule['id']}")
        if rule["proposed_level"] not in ("Required", "Advisory"):
            raise ValueError(f"Unknown proposed level in {rule['id']}")


def render_rules(rules):
    parts = [HEADER, PREAMBLE]
    for rule in rules:
        rid = rule["id"]
        title = f"{rid}: {rule['title']}"
        sources = ", ".join(rule["misra_cpp_ids"]) or "No direct mapping"
        parts.extend(
            [
                f".. _{rid.lower()}:\n\n",
                title + "\n" + "=" * len(title) + "\n\n",
                paragraph(
                    f"**Proposed level:** {rule['proposed_level']}. "
                    f"**Source IDs (MISRA C++:2023):** {sources}."
                ),
                paragraph(f"**Origin:** {rule['origin']}. **Scope:** {rule['scope']}."),
                paragraph(rule["requirement"]),
                paragraph("**Check:** " + rule["enforcement"]),
                paragraph("**Coverage limit:** " + rule["coverage_limit"]),
            ]
        )
    return "".join(parts)


def render_summary(rows):
    summary = io.StringIO(newline="")
    writer = csv.writer(summary, lineterminator="\n")
    writer.writerow(
        [
            "Source ID",
            "MISRust class",
            "Source level",
            "Proposed Rust rules",
            "Assessment",
        ]
    )
    for row in rows:
        links = [
            f":ref:`{rid} <{rid.lower()}>`"
            for rid in filter(None, row["score_rule_ids"].split(";"))
        ]
        disposition = "; ".join(links) or row["score_disposition"].replace("_", " ")
        assessment = (
            row["assessment_note"]
            or "Draft interpretation; applicability and enforcement require review."
        )
        writer.writerow(
            [
                row["misra_cpp_id"],
                row["misrust_class"],
                row["source_category"],
                disposition,
                assessment,
            ]
        )
    return summary.getvalue()


def render():
    payload = json.loads((BASE / "_assets/rules.json").read_text())
    rules = payload["rules"]
    with (BASE / "_assets/applicability.csv").open(newline="") as source:
        rows = list(csv.DictReader(source))
    validate(rules, rows)
    return {
        BASE / "rules.rst": render_rules(rules),
        BASE / "_assets/applicability_summary.csv": render_summary(rows),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if mappings are inconsistent or generated files differ",
    )
    args = parser.parse_args()
    try:
        outputs = render()
    except (ValueError, KeyError) as error:
        print(error, file=sys.stderr)
        return 1
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path))
        else:
            path.write_text(content)
    if stale:
        print(
            "Regenerate with python3 tools/render_rust_coding_rules.py:\n"
            + "\n".join(stale),
            file=sys.stderr,
        )
        return 1
    print(
        f"Validated {EXPECTED_RULES} Rust rules, {EXPECTED_SOURCES} source mappings and all 69 retained "
        "source rules; generated files "
        + ("are current." if args.check else "updated.")
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
