#!/usr/bin/env python3
# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""Render the Rust rule catalogue and mapping table, or check they are current."""

import argparse
import csv
import io
import json
import sys
import textwrap
from collections import Counter
from pathlib import Path

BASE = (
    Path(__file__).resolve().parents[1]
    / "docs/contribute/development/rust/coding_rules"
)
HEADER = """..
   # *******************************************************************************
   # Copyright (c) 2026 Contributors to the Eclipse Foundation
   #
   # See the NOTICE file(s) distributed with this work for additional
   # information regarding copyright ownership.
   #
   # This program and the accompanying materials are made available under the
   # terms of the Apache License Version 2.0 which is available at
   # https://www.apache.org/licenses/LICENSE-2.0
   #
   # SPDX-License-Identifier: Apache-2.0
   # *******************************************************************************

"""
PREAMBLE = """.. Generated by tools/render_rust_coding_rules.py; edit _assets/rules.json instead.

.. _rust_coding_rules:

Rust Rule Catalogue
###################

.. document:: Rust Coding Rules Catalogue
   :id: doc__rust_coding_rules_catalogue
   :status: draft
   :version: 1
   :safety: ASIL_B
   :security: YES
   :realizes: wp__sw_development_plan[version==1]

These are draft rules. The proposed levels take effect only after adoption through the
Software Development Plan as described in :ref:`rust_coding_rules_overview`. Enforcement
candidates require validation under :ref:`rust_coding_rules_verification`; a source mapping
does not establish compliance.

.. contents:: Rules
   :local:
   :depth: 1

"""
EXPECTED_RULES = 43
EXPECTED_SOURCES = 179
EXPECTED_MISRUST_CLASSES = {"C1": 15, "C2": 42, "C3": 53, "C4": 36, "C5": 11, "C6": 22}
EXPECTED_SCRC = {"safe": 54, "unsafe": 38, "not_applicable": 87}
APPLICABLE = {"safe", "unsafe"}
SCRC_LABEL = {"safe": "safe", "unsafe": "unsafe", "not_applicable": "beyond SCRC"}


def paragraph(text):
    return textwrap.fill(text, width=100) + "\n\n"


def validate(rules, rows):
    ids = {r["id"] for r in rules}
    source_ids = {r["misra_cpp_id"] for r in rows}
    if len(ids) != len(rules) or len(source_ids) != len(rows):
        raise ValueError("Duplicate rule or source guideline IDs")
    if len(rules) != EXPECTED_RULES or len(rows) != EXPECTED_SOURCES:
        raise ValueError(
            "Update the documented baseline counts when intentionally changing the catalogue"
        )
    if Counter(r["misrust_class"] for r in rows) != EXPECTED_MISRUST_CLASSES:
        raise ValueError("The MISRust classifications do not match the pinned dataset")
    if Counter(r["scrc_applicability"] for r in rows) != EXPECTED_SCRC:
        raise ValueError(
            "The SCRC applicability verdicts do not match the pinned mapping revision"
        )
    for row in rows:
        gid = row["misra_cpp_id"]
        linked = set(filter(None, row["score_rule_ids"].split(";")))
        expected = {r["id"] for r in rules if gid in r["misra_cpp_ids"]}
        if linked != expected or not linked <= ids:
            raise ValueError(f"Inconsistent rule mapping: {gid}")
        disposition = row["score_disposition"]
        if row["scrc_applicability"] in APPLICABLE:
            wanted = "proposed_rust_obligation" if linked else "rule_assignment_pending"
        else:
            wanted = "retained_beyond_scrc" if linked else "not_applicable"
        if disposition != wanted:
            raise ValueError(
                f"Disposition of {gid} must be {wanted} given its SCRC verdict and rule links"
            )
        if (
            disposition in ("rule_assignment_pending", "retained_beyond_scrc")
            and not row["assessment_note"]
        ):
            raise ValueError(f"{gid} needs an assessment note explaining the open item")
    for rule in rules:
        if not set(rule["misra_cpp_ids"]) <= source_ids:
            raise ValueError(f"Unknown source guideline in {rule['id']}")
        if rule["proposed_level"] not in ("Required", "Advisory"):
            raise ValueError(f"Unknown proposed level in {rule['id']}")


def render_rules(rules, rows):
    verdict = {r["misra_cpp_id"]: SCRC_LABEL[r["scrc_applicability"]] for r in rows}
    parts = [HEADER, PREAMBLE]
    for rule in rules:
        rid = rule["id"]
        title = f"{rid}: {rule['title']}"
        sources = (
            ", ".join(f"{g} ({verdict[g]})" for g in rule["misra_cpp_ids"])
            or "No direct mapping"
        )
        parts.extend(
            [
                f".. _{rid.lower()}:\n\n",
                title + "\n" + "=" * len(title) + "\n\n",
                paragraph(
                    f"**Proposed level:** {rule['proposed_level']}. "
                    f"**Source IDs (MISRA C++:2023, SCRC verdict):** {sources}."
                ),
                paragraph(f"**Origin:** {rule['origin']}. **Scope:** {rule['scope']}."),
                paragraph(rule["requirement"]),
                paragraph("**Check:** " + rule["enforcement"]),
                paragraph("**Coverage limit:** " + rule["coverage_limit"]),
            ]
        )
    return "".join(parts)


def summary_row(row):
    links = [
        f":ref:`{rid} <{rid.lower()}>`"
        for rid in filter(None, row["score_rule_ids"].split(";"))
    ]
    disposition = "; ".join(links) or row["score_disposition"].replace("_", " ")
    assessment = (
        row["assessment_note"]
        or "Draft interpretation; applicability and enforcement require review."
    )
    return [
        row["misra_cpp_id"],
        row["scrc_applicability"].replace("_", " "),
        row["misrust_class"],
        row["source_category"],
        disposition,
        assessment,
    ]


def render_csv(rows):
    out = io.StringIO(newline="")
    writer = csv.writer(out, lineterminator="\n")
    writer.writerow(
        [
            "Source ID",
            "SCRC verdict",
            "MISRust class",
            "Source level",
            "Proposed Rust rules",
            "Assessment",
        ]
    )
    writer.writerows(summary_row(r) for r in rows)
    return out.getvalue()


def render():
    payload = json.loads((BASE / "_assets/rules.json").read_text())
    rules = payload["rules"]
    with (BASE / "_assets/applicability.csv").open(newline="") as source:
        rows = list(csv.DictReader(source))
    validate(rules, rows)
    queue = [
        r
        for r in rows
        if r["score_disposition"] in ("rule_assignment_pending", "retained_beyond_scrc")
    ]
    return {
        BASE / "rules.rst": render_rules(rules, rows),
        BASE / "_assets/applicability_summary.csv": render_csv(rows),
        BASE / "_assets/review_queue.csv": render_csv(queue),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if mappings are inconsistent or generated files differ",
    )
    args = parser.parse_args()
    try:
        outputs = render()
    except (ValueError, KeyError) as error:
        print(error, file=sys.stderr)
        return 1
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path))
        else:
            path.write_text(content)
    if stale:
        print(
            "Regenerate with python3 tools/render_rust_coding_rules.py:\n"
            + "\n".join(stale),
            file=sys.stderr,
        )
        return 1
    print(
        f"Validated {EXPECTED_RULES} Rust rules and {EXPECTED_SOURCES} source mappings against the pinned "
        "SCRC verdicts; generated files "
        + ("are current." if args.check else "updated.")
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
