# *******************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Copyright checks
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
jobs:
  copyright-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Debug Bazel Output Base
        run: bazel info output_base
      - name: List Bazel Cache Contents
        run: ls -lh $(bazel info output_base)

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1
      - name: Run copyright checks
        run: |
          bazel run //:copyright.check
