# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Documentation
on:
  pull_request_target:
    types: [opened, reopened, synchronize]  # Handles forked PRs
  push:
  merge_group:
    types: [checks_requested]

jobs:
  docs-build:
    name: Build documentation
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository (Handle all events)
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref || github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.9.1

      - name: Build documentation
        run: |
          bazel build //docs:github-pages && cp bazel-bin/docs/github-pages.tar .

      - name: Upload artifact for job analysis
        uses: actions/upload-artifact@v4.4.0
        with:
          name: github-pages-${{ github.event.pull_request.head.sha || github.sha }}
          path: github-pages.tar
          retention-days: 1
          if-no-files-found: error

  docs-deploy:
    name: Deploy documentation to GitHub Pages
    permissions:
      pages: write
      id-token: write
      contents: write
      pull-requests: write
    concurrency:
      group: gh-pages
      cancel-in-progress: false
    runs-on: ubuntu-latest
    needs: docs-build
    environment: github-pages  #  Requires approval before execution
    steps:
      - name: Checkout repository (Handle both PR events)
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref || github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Download documentation artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: github-pages-${{ github.event.pull_request.head.sha || github.sha }}

      - name: Untar documentation artifact
        run: mkdir -p extracted_docs && tar -xf github-pages.tar -C extracted_docs

      - name: Deploy 🚀
        id: pages-deployment
        continue-on-error: true
        uses: ./.github/actions/deploy-versioned-pages
        with:
          source_folder: extracted_docs

      - name: Deploy (fallback) 🚀
        id: deployment
        if: ${{ steps.pages-deployment.outcome == 'failure' && github.event_name == 'push' && github.ref_name == 'main' }}
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: github-pages-${{ github.event.pull_request.head.sha || github.sha }}

